### ISSUE TITLE
About commit

### ISSUE THREAD

**Issue by Heyya-x** [light-tech/MiniGit-SampleApp#1]
Could you please give me an example of using of commit?

**Comment by light-tech** [comment]
Can you clarify what you need?

The example already illustrates how to list the commit history.

**Comment by Heyya-x** [comment]
There is a commit function in the MiniGit package, but the example does not explain how to use it.

Could you please give me a example of how to use commit function?

**Comment by light-tech** [comment]
Wouldn't it simply be

       // var repo : GitRepository
       repo.commit("YOUR COMMIT MESSAGE")

? It is supposed to be equivalent to

       git commit -m "YOUR COMMIT MESSAGE"

inside the repository when using the official git command.
